# Generated by Django 5.2 on 2025-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('last_name1', models.CharField(max_length=100)),
                ('last_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('decease_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'artist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('chapters', models.IntegerField()),
                ('editorial', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'manga',
                'managed': False,
            },
        ),
    ]
